### ISSUE TITLE
cool

### ISSUE THREAD

**Issue by Wellaiyo** [fortyMiles/fortymiles.github.io#1]
> 刚看到，确实会玩....   66666~

jekyll 简直酷毙了，还有中英双版和简约大气的style   ，  哈哈

**Comment by Wellaiyo** [comment]
我前两天刚入手了MacBook ， 权哥赐教，如何可以在本地和云服务器之间push

本地操作我差不多都会了 ， 但是怎么建立一个源仓库，可以让其它位置可以执行push等操作呢？就好像之前，你将公司仓库里的代码push到云服务器

**Comment by fortyMiles** [comment]
首先在你的服务器上建立一个git账户（不建可以，但是这样方便管理）
$ sudo adduser git
$ su git
$ cd
$ mkdir .ssh && chmod 700 .ssh
$ touch .ssh/authorized_keys && chmod 600 .ssh/authorized_keys
然后把你自己的key加到authorized_keys里边，
本机执行 $cat /tmp/id_rsa.your.pub然后scp到那个git账户里边，
cat /tmp/id_rsa.your.pub >> ~/.ssh/authorized_keys 
这样你就能ssh访问git这个账户了，也就能方位git服务器了。 
然后在远程服务器上，cd到一个地方去，
$ cd /opt/git
$ mkdir project.git
$ cd project.git
$ git init --bare
Initialized empty Git repository in /opt/git/project.git/
然后在你自己的机器上：
$ cd myproject
$ git init
$ git add .
$ git commit -m 'initial commit'
$ git remote add origin git@gitserver:/opt/git/project.git
$ git push origin master
然后就好了
Best Regard!
Minchiuan Gao
TEL: +86 18857453090

Date: Tue, 3 Nov 2015 19:45:00 -0800

**Comment by mrvgao** [comment]
首先在你的服务器上建立一个git账户（不建可以，但是这样方便管理）

```
$ sudo adduser git
$ su git
$ cd
$ mkdir .ssh && chmod 700 .ssh
$ touch .ssh/authorized_keys && chmod 600 .ssh/authorized_keys
```

然后把你自己的 key 加到 authorized_keys 里边，
本机执行

``` bash
$cat /tmp/id_rsa.your.pub
```

然后 scp 到那个 git 账户里边，然后

``` bash
cat /tmp/id_rsa.your.pub >> ~/.ssh/authorized_keys 
```

这样你就能ssh访问git这个账户了，也就能方位git服务器了。 
然后在远程服务器上，cd到一个地方去，

``` bash
$ cd /opt/git
$ mkdir project.git
$ cd project.git
$ git init --bare
Initialized empty Git repository in /opt/git/project.git/
```

然后在你自己的机器上：

``` bash
$ cd myproject
$ git init
$ git add .
$ git commit -m 'initial commit'
$ git remote add origin git@gitserver:/opt/git/project.git
$ git push origin master
```

然后就好了

具体不了解的话，再看一下git的[官方文档](http://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server)

Reference:
1. [how to set a git server, from git-scm](http://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server)

Best Regard!
Minchiuan Gao
TEL: +86 18857453090

Date: Tue, 3 Nov 2015 19:45:00 -0800

**Comment by Wellaiyo** [comment]
Thanks!

**Comment by Wellaiyo** [comment]
# 聚会、旅游、活动

今天又是一个双十一，单身的我们很无聊，很无奈，想出去玩，想出去嗨，但是约不到人，不知道约谁。

而像我这样的人占大多数，是不是想到什么？很邪门对不对？

大家都想约出去玩，却因为一些莫名的因素，没有聚在一起。

这个时候应该喊一句口号：“想出去玩，就大声说出来！”

我想在我想出去玩的时候，能找到有同样想法的小伙伴，我想让更多的人走出房门，去拥抱外面的世界。

拒绝孤单，拒绝宅，拒绝单调的娱乐活动，拒绝充满负能量的生活。 Go out, with others!

> Go out! To find more friends, to see the scenery outside.

我想去某个地方，一个人总是会感觉很孤单，所以我要找更多的人陪我一起去。 Create！

我想去找更多的朋友，陪他们去各处看风景，谈心情。 Find！
- 旅游——去大理、去西藏，世界那么大，我想去看看
- 聚会——老朋友、老同学，好多年不见了，出来喝杯小酒，吹吹牛皮
- 活动——大学生活的圈子总是那么的小，每天都在宿舍打游戏？讨厌这样的自己？约几个人出去看看海吧，拥抱阳光

———— 也许，你还能遇见那个他（她）。缘分这种东西，谁又说得准呢

它的未来应该是这样的：
- 某一天，微博、朋友圈、现实社交，会疯狂的传递这样一种理念。
- 以后会流行一个词，时尚而充满正能量，这个词表示爱聚会爱社交爱旅游的一类人。这个词和这个产品会产生一种情怀，大家以这个词自称。
- 大学生市场是产品市场开拓的基础，然后是刚毕业不久的青年男女。
- 总有一天，必将改变年轻人的生活旋律，并传递一种正能量。找到最好的风景，找到最好的朋友，找到最好的自己。

**Comment by Wellaiyo** [comment]
也许有人做过这样的，但是我觉得我们没用上，就相当于没人做过  0.0
